<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-81OO9KQ" name="KeywordsPractice.TimeoutsKeywordPractice" tests="6" failures="0" timestamp="2022-09-22T14:34:07 IST" time="5.073" errors="1">
  <testcase name="HomePageTest" time="5.031" classname="KeywordsPractice.TimeoutsKeywordPractice">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method KeywordsPractice.TimeoutsKeywordPractice.HomePageTest() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method KeywordsPractice.TimeoutsKeywordPractice.HomePageTest() didn't finish within the time-out 5000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- HomePageTest -->
  <system-out/>
  <testcase name="NotificationPageTest" time="0.015" classname="KeywordsPractice.TimeoutsKeywordPractice"/>
  <system-out/>
  <testcase name="NotificationPageTest" time="0.008" classname="KeywordsPractice.TimeoutsKeywordPractice"/>
  <system-out/>
  <testcase name="NotificationPageTest" time="0.006" classname="KeywordsPractice.TimeoutsKeywordPractice"/>
  <system-out/>
  <testcase name="NotificationPageTest" time="0.007" classname="KeywordsPractice.TimeoutsKeywordPractice"/>
  <system-out/>
  <testcase name="NotificationPageTest" time="0.006" classname="KeywordsPractice.TimeoutsKeywordPractice"/>
  <system-out/>
</testsuite> <!-- KeywordsPractice.TimeoutsKeywordPractice -->
